export const productsData = [
  {
    id: 1,
    img: "flower1.svg",
    name: "Барбарис Тунберга Кобольд Berberis thunbergii Kobold С3,6",
    type: "Лиственные кустарники",
    discountPrice: 2800,
    price: 5200,
    hit: true,
    stock: true,
    new: false,
  },
  {
    id: 2,
    img: "flower2.svg",
    name: "Барбарис Тунберга Кобольд Berberis thunbergii Kobold С3,6",
    type: "Лиственные кустарники",
    discountPrice: 2800,
    price: 5200,
    hit: false,
    stock: false,
    new: false,
  },
  {
    id: 3,
    img: "flower3.svg",
    name: "Барбарис Тунберга Кобольд Berberis thunbergii Kobold С3,6",
    type: "Лиственные кустарники",
    discountPrice: 2800,
    price: 5200,
    hit: true,
    stock: true,
    new: false,
  },
  {
    id: 4,
    img: "flower4.svg",
    name: "Барбарис Тунберга Кобольд Berberis thunbergii Kobold С3,6",
    type: "Лиственные кустарники",
    discountPrice: 2800,
    price: 5200,
    hit: false,
    stock: false,
    new: true,
  },
  {
    id: 5,
    img: "flower5.svg",
    name: "Барбарис Тунберга Кобольд Berberis thunbergii Kobold С3,6",
    type: "Лиственные кустарники",
    discountPrice: 2800,
    price: 5200,
    hit: false,
    stock: true,
    new: false,
  },
  {
    id: 6,
    img: "flower1.svg",
    name: "Барбарис Тунберга Кобольд Berberis thunbergii Kobold С3,6",
    type: "Лиственные кустарники",
    discountPrice: 2800,
    price: 5200,
    hit: false,
    stock: false,
    new: false,
  },
];
